#!/usr/bin/env python3
"""Render the per-audience RAG corpora from front matter.

A guide is a QUERY, not a directory — see docs/audience-projection.md.  This
script is the query, and `corpus/` is its render: never edited, never
committed, regenerable from the tree at any time.

The vocabulary this reads (`audience`, `also_reaches`, `status`, `tags`,
`tethered_to`) is declared in docs/pedagogy-authoring.md.  That file is the
authority; if the two disagree, the schema is right and this script is wrong.
"""
import os
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "corpus"

# Held back from every corpus.  `scaffold` is unfinished; `proposed` is
# finished but unratified — an agent quoting an unruled rule as policy is the
# specific failure this gate exists to prevent.
WITHHOLD = {"scaffold", "proposed"}

# The four guides are the four declared audience values, finally used.
GUIDES = {
    "student-guide": "student",
    "instructor-guide": "faculty",
    "platform-guide": "builder",
    "dev-guide": "operator",
}

# SecurityBot3000 is a CROSS-CUT, not an audience — it queries tags instead,
# which is what keeps the audience enum from becoming a junk drawer.  These
# are the Controls group plus the architecture tags that describe the
# chokepoint (docs/pedagogy-authoring.md).
SECURITY_TAGS = {
    "access-control", "rbac", "least-privilege", "secrets-management",
    "escrow", "key-rotation", "encryption-at-rest", "encryption-in-transit",
    "audit-logging", "egress-control", "allowlist", "sso", "oidc",
    "identity-broker", "tenancy", "isolation", "multi-tenant", "gateway",
    "chokepoint", "supply-chain",
}
SECURITY_MIN = 3   # below this it's a passing mention, not a security page


def load(path: pathlib.Path):
    text = path.read_text()
    if not text.startswith("---\n"):
        return None, text
    _, fm, body = text.split("---", 2)
    return yaml.safe_load(fm) or {}, body.lstrip("\n")


def flat_name(rel: pathlib.Path) -> str:
    """apex/your-data/who-can-see-it.md -> your-data--who-can-see-it.md"""
    parts = list(rel.parts)
    if parts[0] in ("apex", "docs"):
        parts = parts[1:]
    return "--".join(parts)


def main() -> int:
    pages, unlabelled = [], []
    for base in ("apex", "docs"):
        for path in sorted((ROOT / base).rglob("*.md")):
            rel = path.relative_to(ROOT)
            fm, body = load(path)
            if fm is None:
                unlabelled.append(rel)
                continue
            pages.append((rel, fm, body))

    if OUT.exists():
        for p in sorted(OUT.rglob("*"), reverse=True):
            p.unlink() if p.is_file() else p.rmdir()
    OUT.mkdir(parents=True, exist_ok=True)

    corpora, withheld = {}, []
    for rel, fm, body in pages:
        status = fm.get("status", "scaffold")
        if status in WITHHOLD:
            withheld.append((rel, status))
            continue
        reach = {fm.get("audience")} | set(fm.get("also_reaches") or [])
        for guide, audience in GUIDES.items():
            if audience in reach:
                corpora.setdefault(guide, []).append((rel, fm, body))
        if len(set(fm.get("tags") or []) & SECURITY_TAGS) >= SECURITY_MIN:
            corpora.setdefault("securitybot3000", []).append((rel, fm, body))

    tethers = {}
    for guide, entries in sorted(corpora.items()):
        d = OUT / guide
        d.mkdir(parents=True, exist_ok=True)
        lines = [f"# {guide} — corpus manifest", "",
                 f"{len(entries)} pages, rendered by `just docs-corpus`.  "
                 "Do not edit anything in this directory — edit the source page.", "",
                 "| page | source | audience | also_reaches | status |",
                 "|---|---|---|---|---|"]
        for rel, fm, body in sorted(entries):
            name = flat_name(rel)
            # The description is the chunker's context; keep it with the text.
            head = f"<!-- source: {rel} | audience: {fm.get('audience')} | status: {fm.get('status')} -->\n"
            (d / name).write_text(head + f"> {fm.get('description', '')}\n\n" + body)
            lines.append(f"| `{name}` | `{rel}` | {fm.get('audience')} | "
                         f"{', '.join(fm.get('also_reaches') or []) or '—'} | {fm.get('status')} |")
            for t in fm.get("tethered_to") or []:
                tethers.setdefault(str(t), set()).add(guide)
        (d / "MANIFEST.md").write_text("\n".join(lines) + "\n")

    report = ["# corpus/ — rendered, not edited", "",
              "Generated by `just docs-corpus` from front matter.  "
              "See [docs/audience-projection.md](../docs/audience-projection.md).", "",
              "## Corpora", "", "| guide | query | pages |", "|---|---|---|"]
    for guide, entries in sorted(corpora.items()):
        q = (f"`audience: {GUIDES[guide]}` or `also_reaches` contains it"
             if guide in GUIDES else f"≥{SECURITY_MIN} security tags (cross-cut)")
        report += [f"| {guide} | {q} | {len(entries)} |"]
    report += ["", "## Withheld", "",
               "Held back by status — unfinished, or finished but unratified.", "",
               "| page | status |", "|---|---|"]
    report += [f"| `{rel}` | {st} |" for rel, st in sorted(withheld)] or ["| — | — |"]
    if unlabelled:
        report += ["", "## Unlabelled — in no corpus at all", "",
                   "These carry no front matter, so no query can reach them.", ""]
        report += [f"- `{rel}`" for rel in sorted(unlabelled)]
    report += ["", "## Drift index", "",
               "Which corpora go stale when a source path changes "
               "(`tethered_to`, the machine-readable half of the drift rule).", "",
               "| path | corpora |", "|---|---|"]
    report += [f"| `{p}` | {', '.join(sorted(g))} |" for p, g in sorted(tethers.items())]
    (OUT / "README.md").write_text("\n".join(report) + "\n")

    for guide, entries in sorted(corpora.items()):
        print(f"  {guide:22} {len(entries):3} pages")
    print(f"  {'withheld':22} {len(withheld):3} pages")
    if unlabelled:
        print(f"  {'UNLABELLED':22} {len(unlabelled):3} pages -> in no corpus")
        for rel in sorted(unlabelled):
            print(f"      {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
